[package]
name = "vyronax/cmdr"
description = "Cmdr Fork."
version = "1.12.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
exclude = ["assets", "docs"]
include = ["CHANGELOG.md", "Cmdr", "default.project.json", "LICENSE"]

[dependencies]
